[tool.poetry]
name = "airflow-providers-wherobots"
version = "0.1.0"
description = "Airflow extension for communicating with Wherobots Cloud"
authors = ["zongsi.zhang <zongsi@wherobots.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9, <3.13"
wherobots-python-dbapi = {git = "https://github.com/wherobots/wherobots-python-dbapi-driver", rev = "3025aaf"}

[tool.poetry.group.dev.dependencies]
apache-airflow = "^2.7.0"
pytest = "^8.1.1"
requests-mock = "^1.12.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
